### ISSUE TITLE
issue about language

### ISSUE THREAD

**Issue by dengjl** [jacobeisenstein/bayes-seg#1]
I  am very appreciate for your work. Now I have a problem that when applied it to Chinese materials, it seems not work. And arise such exception

java.lang.ArrayIndexOutOfBoundsException: 0
	at edu.mit.nlp.segmenter.dp.I2JInterface.makeDPDoc(I2JInterface.java:14)
	at edu.mit.nlp.segmenter.dp.BayesWrapper.segmentTexts(BayesWrapper.java:44)
	at edu.mit.nlp.segmenter.SegTester.main(SegTester.java:131)
Usage: SegTester -config config -dir dir -suff suff [-out out] -segmenter <bayes|mcs|ui> -options options

Do you have any idea of this?

**Comment by reubenbf** [comment]
having a similar issue and need some help as well
